# Generated by Django 4.1.1 on 2022-09-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_admin_passwordhistory_delete_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
