# Generated by Django 4.1.1 on 2022-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=300)),
                ('address', models.CharField(default=None, max_length=100)),
                ('status', models.CharField(default=None, max_length=10)),
                ('logo_url', models.CharField(default=None, max_length=1000)),
                ('banner_url', models.CharField(default=None, max_length=1000)),
                ('owner_id', models.ManyToManyField(to='api.account')),
            ],
        ),
    ]
