# Generated by Django 4.0.6 on 2022-09-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_school_delete_item_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='school',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='school',
            name='owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
