# Generated by Django 4.0.6 on 2022-09-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
