# Generated by Django 4.0.6 on 2022-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_school_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_status',
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
