# Generated by Django 4.1.1 on 2022-09-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_courses_type_id_courses_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openrequests',
            old_name='proof_of_payment_ur',
            new_name='proof_of_payment_url',
        ),
        migrations.RenameField(
            model_name='openrequests',
            old_name='requesst_status',
            new_name='request_status',
        ),
    ]
