# Generated by Django 4.1.1 on 2022-09-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_proof_of_payment_ur_openrequests_proof_of_payment_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openrequests',
            old_name='requese_timestamp',
            new_name='request_timestamp',
        ),
    ]
