# Generated by Django 4.1.1 on 2022-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_requese_timestamp_openrequests_request_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseType',
        ),
        migrations.AlterField(
            model_name='courses',
            name='type',
            field=models.CharField(choices=[('NONE', 'NONE'), ('MATH', 'MATH')], default='NONE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('course', 'account')},
        ),
    ]
