# Generated by Django 4.1.1 on 2022-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_coursetype_alter_courses_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
