# Generated by Django 4.1.1 on 2022-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_coursehistory_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrooms',
            name='room_descripition',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
