# Generated by Django 4.1.1 on 2022-09-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_schoolrooms_room_descripition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolrooms',
            old_name='room_descripition',
            new_name='room_description',
        ),
    ]
