# Generated by Django 4.1.1 on 2022-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_room_descripition_schoolrooms_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrooms',
            name='room_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
