# Generated by Django 4.1.1 on 2022-09-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_schoolrooms_room_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolrooms',
            old_name='room_description',
            new_name='description',
        ),
    ]
