# Generated by Django 4.1.1 on 2022-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_room_description_schoolrooms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrooms',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
