# Generated by Django 4.1.2 on 2022-10-06 08:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_reservation_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_pic',
            field=models.ImageField(default=None, null=True, upload_to=api.models.upload_payment),
        ),
    ]
