# Generated by Django 4.1.2 on 2022-10-10 08:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_reservation_payment_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openrequests',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='openrequests',
            name='proof_of_payment_url',
        ),
        migrations.AddField(
            model_name='openrequests',
            name='document',
            field=models.ImageField(default=None, null=True, upload_to=api.models.upload_payment),
        ),
        migrations.AddField(
            model_name='openrequests',
            name='payment_pic',
            field=models.ImageField(default=None, null=True, upload_to=api.models.upload_payment),
        ),
    ]
