# Generated by Django 4.1.2 on 2022-10-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_remove_school_address_school_addr_description_and_more"),
        ("api", "0032_alter_openrequests_document"),
    ]

    operations = []
