# Generated by Django 4.1.2 on 2022-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_merge_20221012_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="expire_date",
            field=models.DateField(blank=True, default=None),
        ),
    ]
