# Generated by Django 4.1.2 on 2022-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_notification_expire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="create_time",
            field=models.DateTimeField(default=None),
        ),
    ]
