# Generated by Django 4.1.2 on 2022-10-18 14:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_notification_create_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="banner_url",
        ),
        migrations.RemoveField(
            model_name="school",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="school",
            name="banner_pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to=api.models.upload_banner
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="logo_pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to=api.models.upload_logo
            ),
        ),
    ]
