# Generated by Django 4.1.2 on 2022-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_school_banner_url_remove_school_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytime',
            name='end_time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='studytime',
            name='start_time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
