# Generated by Django 4.1.2 on 2022-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_studytimerecords_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='token_expire',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
