# Generated by Django 4.1.2 on 2022-11-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_account_token_account_token_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openrequests",
            name="request_status",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
