# Generated by Django 4.1.2 on 2022-11-10 11:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_openrequests_request_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="payment_method_picture_url",
        ),
        migrations.AddField(
            model_name="courses",
            name="payment_method_pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to=api.models.upload_method
            ),
        ),
        migrations.AddField(
            model_name="courses",
            name="school_name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
