# Generated by Django 4.1.2 on 2022-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_account_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
