# Generated by Django 4.1.2 on 2022-11-11 08:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="profile_picture",
            field=models.ImageField(
                default=None, null=True, upload_to=api.models.upload_profile
            ),
        ),
    ]
