# Generated by Django 4.1.2 on 2022-11-11 08:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_alter_account_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="course_pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to=api.models.upload_poster
            ),
        ),
    ]
