# Generated by Django 4.1.2 on 2022-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="status",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
